//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int IDReport { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDService { get; set; }
        public string Documents { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }
        public virtual Services Services { get; set; }
    }
}
