//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Classes
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.Reports = new HashSet<Reports>();
        }
    
        public int IDService { get; set; }
        public string Title { get; set; }
        public string Time { get; set; }
        public string Img { get; set; }
        public string Price { get; set; }
        public Nullable<double> Discount { get; set; }
        private BitmapImage discountImage;
        public BitmapImage DiscountImage
        {
            get { return Discount != null ? DiscountImage = new BitmapImage(new Uri("/Resources/discount.png", UriKind.Relative)) : null; }
            set { discountImage = value; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
